import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import { Booking } from "../models/Booking.js";
import { Driver } from "../models/Driver.js";
import { Invoice } from "../models/Invoice.js";
import { Payment } from "../models/Payment.js";
import { Trip } from "../models/Trip.js";
import { Vehicle } from "../models/Vehicle.js";

const reportTitles = {
  "daily-trips": "Daily Trip Reports",
  drivers: "Driver Wise Reports",
  vehicles: "Vehicle Wise Reports",
  bookings: "Booking Reports",
  invoices: "Invoice Reports",
  payments: "Payment Reports",
  revenue: "Revenue Reports",
  "pending-payments": "Pending Payment Reports",
  gst: "GST Reports",
  utilization: "Utilization Reports",
  custom: "Custom Reports"
};

export async function summaryReport() {
  const [tripCount, invoiceCount, bookingCount, revenue] = await Promise.all([
    Trip.countDocuments({ status: "Completed" }),
    Invoice.countDocuments(),
    Booking.countDocuments(),
    Invoice.aggregate([{ $group: { _id: null, total: { $sum: "$finalAmount" }, outstanding: { $sum: "$balanceAmount" }, gst: { $sum: "$gstAmount" } } }])
  ]);
  return {
    bookingCount,
    tripCount,
    invoiceCount,
    revenue: revenue[0]?.total || 0,
    outstanding: revenue[0]?.outstanding || 0,
    gst: revenue[0]?.gst || 0
  };
}

export async function getReport(type, query = {}) {
  const normalizedType = reportTitles[type] ? type : "daily-trips";
  const builders = {
    "daily-trips": dailyTripsReport,
    drivers: driverReport,
    vehicles: vehicleReport,
    bookings: bookingReport,
    invoices: invoiceReport,
    payments: paymentReport,
    revenue: revenueReport,
    "pending-payments": pendingPaymentReport,
    gst: gstReport,
    utilization: utilizationReport,
    custom: bookingReport
  };
  const report = await builders[normalizedType](query);
  return { type: normalizedType, title: reportTitles[normalizedType], ...report };
}

export async function reportExcelBuffer(type, query) {
  const report = await getReport(type, query);
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet(report.title.slice(0, 31));
  sheet.columns = report.columns.map((column) => ({ header: column.header, key: column.key, width: 22 }));
  sheet.addRows(report.rows);
  sheet.getRow(1).font = { bold: true };
  return workbook.xlsx.writeBuffer();
}

export async function reportPdfBuffer(type, query) {
  const report = await getReport(type, query);
  const doc = new PDFDocument({ margin: 36, size: "A4", layout: "landscape" });
  const chunks = [];
  doc.on("data", (chunk) => chunks.push(chunk));
  const done = new Promise((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))));
  doc.fontSize(18).text("Cab Management ERP", { align: "center" });
  doc.fontSize(13).text(report.title, { align: "center" });
  doc.moveDown(0.5).fontSize(9).text(`Generated: ${new Date().toLocaleString()}`);
  doc.text(`Filters: ${JSON.stringify(cleanQuery(query))}`);
  doc.moveDown();
  const headers = report.columns.slice(0, 8);
  doc.fontSize(8).font("Helvetica-Bold");
  headers.forEach((column, index) => doc.text(column.header, 36 + index * 92, doc.y, { width: 88, continued: index < headers.length - 1 }));
  doc.moveDown();
  doc.font("Helvetica");
  report.rows.slice(0, 35).forEach((row) => {
    headers.forEach((column, index) => doc.text(String(row[column.key] ?? ""), 36 + index * 92, doc.y, { width: 88, continued: index < headers.length - 1 }));
    doc.moveDown();
  });
  doc.moveDown().fontSize(8).text("Generated by Cab Management ERP", { align: "center" });
  doc.end();
  return done;
}

async function dailyTripsReport(query) {
  const trips = await Trip.find(dateFilter(query, "createdAt")).populate("booking driver vehicle").sort({ createdAt: -1 }).lean();
  const rows = trips.map((trip) => ({
    tripId: trip.tripNumber,
    bookingId: trip.booking?.bookingId,
    passengerName: trip.booking?.passengerName,
    driverName: trip.driver?.driverName,
    vehicleNumber: trip.vehicle?.registrationNumber,
    pickupLocation: trip.booking?.pickupLocation || trip.booking?.reportingAddress,
    dropLocation: trip.booking?.dropLocation || trip.booking?.dropAddress,
    timeOut: formatDate(trip.timeOut),
    timeIn: formatDate(trip.timeIn),
    totalKm: trip.totalKm || 0,
    tollCharges: trip.tollCharges || 0,
    parkingCharges: trip.parkingCharges || 0,
    extraCharges: trip.extraCharges || 0,
    finalAmount: (trip.totalKm || 0) * (trip.vehicle?.ratePerKm || 0) + (trip.tollCharges || 0) + (trip.parkingCharges || 0) + (trip.extraCharges || 0),
    tripStatus: trip.status
  }));
  return withCommon("daily-trips", rows, [
    ["tripId", "Trip ID"], ["bookingId", "Booking ID"], ["passengerName", "Passenger"], ["driverName", "Driver"], ["vehicleNumber", "Vehicle"], ["pickupLocation", "Pickup"], ["dropLocation", "Drop"], ["timeOut", "Time Out"], ["timeIn", "Time In"], ["totalKm", "Total KM"], ["tollCharges", "Toll"], ["parkingCharges", "Parking"], ["extraCharges", "Extras"], ["finalAmount", "Final Amount"], ["tripStatus", "Status"]
  ]);
}

async function driverReport() {
  const [drivers, trips] = await Promise.all([Driver.find().lean(), Trip.find().populate("driver vehicle").lean()]);
  const rows = drivers.map((driver) => {
    const driverTrips = trips.filter((trip) => String(trip.driver?._id) === String(driver._id));
    const totalKm = sum(driverTrips, "totalKm");
    return {
      driverName: driver.driverName,
      contactNumber: driver.contactNumber,
      totalTrips: driverTrips.length,
      totalKm,
      totalRevenue: driverTrips.reduce((n, trip) => n + (trip.totalKm || 0) * (trip.vehicle?.ratePerKm || 0), 0),
      averageKm: driverTrips.length ? Number((totalKm / driverTrips.length).toFixed(2)) : 0,
      activeDays: new Set(driverTrips.map((trip) => trip.createdAt?.toDateString())).size,
      lastTripDate: formatDate(driverTrips.at(-1)?.createdAt),
      driverStatus: driver.status
    };
  });
  return withCommon("drivers", rows, [["driverName", "Driver"], ["contactNumber", "Contact"], ["totalTrips", "Trips"], ["totalKm", "KM"], ["totalRevenue", "Revenue"], ["averageKm", "Avg KM"], ["activeDays", "Active Days"], ["lastTripDate", "Last Trip"], ["driverStatus", "Status"]]);
}

async function vehicleReport() {
  const [vehicles, trips] = await Promise.all([Vehicle.find().lean(), Trip.find().populate("vehicle").lean()]);
  const rows = vehicles.map((vehicle) => {
    const vehicleTrips = trips.filter((trip) => String(trip.vehicle?._id) === String(vehicle._id));
    return {
      vehicleNumber: vehicle.registrationNumber,
      vehicleType: vehicle.vehicleType,
      totalTrips: vehicleTrips.length,
      totalKm: sum(vehicleTrips, "totalKm"),
      revenueGenerated: vehicleTrips.reduce((n, trip) => n + (trip.totalKm || 0) * (vehicle.ratePerKm || 0), 0),
      maintenanceStatus: vehicle.maintenanceNotes || "Clear",
      availabilityStatus: vehicle.status,
      lastTripDate: formatDate(vehicleTrips.at(-1)?.createdAt),
      insuranceExpiry: formatDate(vehicle.insuranceExpiry),
      fitnessExpiry: formatDate(vehicle.fitnessCertificateExpiry)
    };
  });
  return withCommon("vehicles", rows, [["vehicleNumber", "Vehicle"], ["vehicleType", "Type"], ["totalTrips", "Trips"], ["totalKm", "KM"], ["revenueGenerated", "Revenue"], ["maintenanceStatus", "Maintenance"], ["availabilityStatus", "Status"], ["lastTripDate", "Last Trip"], ["insuranceExpiry", "Insurance"], ["fitnessExpiry", "Fitness"]]);
}

async function bookingReport(query) {
  const bookings = await Booking.find({ ...dateFilter(query, "createdAt"), ...(query.status ? { status: query.status } : {}) }).sort({ createdAt: -1 }).lean();
  const rows = bookings.map((booking) => ({
    bookingId: booking.bookingId,
    cabRequestNumber: booking.cabRequestNumber,
    passengerName: booking.passengerName,
    businessUnit: booking.businessUnit,
    pickupLocation: booking.pickupLocation || booking.reportingAddress,
    dropLocation: booking.dropLocation || booking.dropAddress,
    carType: booking.carType,
    travelDate: formatDate(booking.travelStartDate),
    employeeCount: booking.employeeCount,
    projectCode: booking.costCenter,
    bookingStatus: booking.status
  }));
  return withCommon("bookings", rows, [["bookingId", "Booking"], ["cabRequestNumber", "Request No"], ["passengerName", "Passenger"], ["businessUnit", "Business Unit"], ["pickupLocation", "Pickup"], ["dropLocation", "Drop"], ["carType", "Car Type"], ["travelDate", "Travel Date"], ["employeeCount", "Employees"], ["projectCode", "Project Code"], ["bookingStatus", "Status"]]);
}

async function invoiceReport(query) {
  const invoices = await Invoice.find({ ...dateFilter(query, "createdAt"), ...(query.status ? { status: query.status } : {}) }).populate("booking trip").sort({ createdAt: -1 }).lean();
  const rows = invoices.map((invoice) => ({
    invoiceNumber: invoice.invoiceNumber,
    invoiceDate: formatDate(invoice.createdAt),
    passengerName: invoice.booking?.passengerName,
    businessUnit: invoice.booking?.businessUnit || invoice.clientName,
    totalKm: invoice.trip?.totalKm || 0,
    baseAmount: invoice.subtotal,
    gstAmount: invoice.gstAmount,
    extraCharges: (invoice.trip?.extraCharges || 0) + (invoice.trip?.tollCharges || 0) + (invoice.trip?.parkingCharges || 0),
    finalAmount: invoice.finalAmount,
    paymentStatus: invoice.balanceAmount === 0 ? "Paid" : invoice.paidAmount > 0 ? "Partial" : "Pending",
    invoiceStatus: invoice.status
  }));
  return withCommon("invoices", rows, [["invoiceNumber", "Invoice"], ["invoiceDate", "Date"], ["passengerName", "Passenger"], ["businessUnit", "Business Unit"], ["totalKm", "KM"], ["baseAmount", "Base"], ["gstAmount", "GST"], ["extraCharges", "Extras"], ["finalAmount", "Final"], ["paymentStatus", "Payment"], ["invoiceStatus", "Status"]]);
}

async function paymentReport() {
  const payments = await Payment.find().populate("invoice").sort({ createdAt: -1 }).lean();
  const rows = payments.map((payment) => ({
    invoiceNumber: payment.invoice?.invoiceNumber,
    paymentDate: formatDate(payment.paymentDate),
    paymentAmount: payment.amount,
    outstandingAmount: payment.invoice?.balanceAmount,
    paymentMode: payment.method,
    referenceNumber: payment.referenceNumber,
    transactionId: payment._id,
    clientName: payment.invoice?.clientName,
    paymentStatus: payment.invoice?.status
  }));
  return withCommon("payments", rows, [["invoiceNumber", "Invoice"], ["paymentDate", "Date"], ["paymentAmount", "Amount"], ["outstandingAmount", "Outstanding"], ["paymentMode", "Mode"], ["referenceNumber", "Reference"], ["transactionId", "Transaction"], ["clientName", "Client"], ["paymentStatus", "Status"]]);
}

async function revenueReport() {
  const invoices = await Invoice.find().lean();
  const grouped = groupByMonth(invoices);
  const rows = Object.entries(grouped).map(([month, list]) => ({
    month,
    totalTrips: list.length,
    revenue: sum(list, "finalAmount"),
    gst: sum(list, "gstAmount"),
    netEarnings: sum(list, "subtotal"),
    expenses: 0,
    profit: sum(list, "subtotal")
  }));
  return withCommon("revenue", rows, [["month", "Month"], ["totalTrips", "Trips"], ["revenue", "Revenue"], ["gst", "GST"], ["netEarnings", "Net"], ["expenses", "Expenses"], ["profit", "Profit"]]);
}

async function pendingPaymentReport() {
  const invoices = await Invoice.find({ balanceAmount: { $gt: 0 } }).sort({ dueDate: 1 }).lean();
  const rows = invoices.map((invoice) => ({
    invoiceNumber: invoice.invoiceNumber,
    clientName: invoice.clientName,
    invoiceDate: formatDate(invoice.createdAt),
    dueDate: formatDate(invoice.dueDate),
    pendingAmount: invoice.balanceAmount,
    daysOutstanding: Math.max(Math.floor((Date.now() - new Date(invoice.createdAt)) / 86400000), 0),
    contactPerson: invoice.clientEmail,
    paymentStatus: invoice.status
  }));
  return withCommon("pending-payments", rows, [["invoiceNumber", "Invoice"], ["clientName", "Client"], ["invoiceDate", "Invoice Date"], ["dueDate", "Due Date"], ["pendingAmount", "Pending"], ["daysOutstanding", "Days"], ["contactPerson", "Contact"], ["paymentStatus", "Status"]]);
}

async function gstReport(query) {
  const invoices = await Invoice.find(dateFilter(query, "createdAt")).sort({ createdAt: -1 }).lean();
  const rows = invoices.map((invoice) => ({
    invoiceNumber: invoice.invoiceNumber,
    invoiceDate: formatDate(invoice.createdAt),
    baseAmount: invoice.subtotal,
    gstPercentage: invoice.gstPercent,
    gstAmount: invoice.gstAmount,
    finalAmount: invoice.finalAmount
  }));
  return withCommon("gst", rows, [["invoiceNumber", "Invoice"], ["invoiceDate", "Date"], ["baseAmount", "Taxable"], ["gstPercentage", "GST %"], ["gstAmount", "GST"], ["finalAmount", "Final"]]);
}

async function utilizationReport() {
  const [trips, drivers, vehicles, bookings] = await Promise.all([Trip.find().lean(), Driver.find().lean(), Vehicle.find().lean(), Booking.find().lean()]);
  const rows = [
    { metric: "Driver Utilization", value: drivers.length ? `${Math.round((drivers.filter((d) => d.status === "In Trip").length / drivers.length) * 100)}%` : "0%" },
    { metric: "Vehicle Utilization", value: vehicles.length ? `${Math.round((vehicles.filter((v) => v.status === "In Trip").length / vehicles.length) * 100)}%` : "0%" },
    { metric: "Booking Completion Rate", value: bookings.length ? `${Math.round((trips.filter((t) => t.status === "Completed").length / bookings.length) * 100)}%` : "0%" },
    { metric: "Average Trip Duration", value: `${average(trips, "totalHours")} hrs` }
  ];
  return withCommon("utilization", rows, [["metric", "Metric"], ["value", "Value"]]);
}

function withCommon(type, rows, columnPairs) {
  const columns = columnPairs.map(([key, header]) => ({ key, header }));
  return {
    columns,
    rows,
    summary: summarize(rows),
    charts: {
      trend: rows.slice(0, 12).map((row, index) => ({ name: row.month || row.invoiceDate || row.travelDate || row.tripId || String(index + 1), value: row.finalAmount || row.revenue || row.totalTrips || row.totalKm || row.pendingAmount || 0 })),
      status: statusBreakdown(rows)
    },
    filters: { supportsDateRange: true, supportsSearch: true, supportsExport: true },
    type
  };
}

function summarize(rows) {
  return {
    records: rows.length,
    totalKm: sum(rows, "totalKm"),
    totalRevenue: sum(rows, "finalAmount") || sum(rows, "revenue") || sum(rows, "revenueGenerated") || sum(rows, "totalRevenue"),
    pendingAmount: sum(rows, "pendingAmount"),
    gstAmount: sum(rows, "gstAmount")
  };
}

function statusBreakdown(rows) {
  const counts = {};
  for (const row of rows) {
    const status = row.status || row.tripStatus || row.invoiceStatus || row.paymentStatus || row.bookingStatus || row.driverStatus || row.availabilityStatus;
    if (status) counts[status] = (counts[status] || 0) + 1;
  }
  return Object.entries(counts).map(([name, value]) => ({ name, value }));
}

function dateFilter(query, field) {
  const filter = {};
  if (query.from || query.to) {
    filter[field] = {};
    if (query.from) filter[field].$gte = new Date(query.from);
    if (query.to) filter[field].$lte = new Date(query.to);
  }
  return filter;
}

function groupByMonth(items) {
  return items.reduce((acc, item) => {
    const date = new Date(item.createdAt);
    const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
    acc[key] = acc[key] || [];
    acc[key].push(item);
    return acc;
  }, {});
}

function sum(items, key) {
  return items.reduce((total, item) => total + Number(item[key] || 0), 0);
}

function average(items, key) {
  return items.length ? Number((sum(items, key) / items.length).toFixed(2)) : 0;
}

function formatDate(value) {
  return value ? new Date(value).toLocaleString() : "";
}

function cleanQuery(query) {
  return Object.fromEntries(Object.entries(query || {}).filter(([, value]) => value));
}
